path: ".."
plugins:
  - name: countMergeCommits
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les MergeCommits par personne
        width: 600
  - name: countLines
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les MergeCommits par personne
        width: 600
