path: ".."
plugins:
  - name: countMergeCommits
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les merge commits par personne
        date: 2021-11-01~2021-12-01
  - name: countLinesOverTime
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les lignes ajoutées par personne
        author: .*Claire.*
  - name: countFilesChanged
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Afficher les fichiers les plus changés
        width: 600
      toggleOptions:
        - nocolor
        - cute
