path: ".."
plugins:
  - name: countCommits
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les MergeCommits par personne
        width: 600
        date: 2021-10-12~2021-11-12
        author: ".*Claire.*"
      toggleOptions:
        - nocolor
        - cute
