path: "."
plugins:
  - name: countLinesPerCommitPerAuthor
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les lignes par commits par personne
  - name: countLinesOverTime
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les lignes ajoutées par jour
        author: .*Claire.*
  - name: countFilesChanged
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les commits par personne
