path: "."
plugins:
  - name: CountAverageLinesPerCommitPerAuthor
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les merge commits par personne
        date: 2021-11-01~2021-12-01
  - name: countLinesOverTime
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les lignes ajoutées par jour
        author: .*Claire.*
  - name: countFilesChanged
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les commits par personne
