path: ".."
plugins:
  - name: countMergeCommits
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les merge commits par personne
        date: 2021-11-01~2021-12-01
  - name: countLines
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les lignes ajoutées par personne
        author: .*Claire.*
  - name: countCommits
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les commits par personne
