path: "."
plugins:
  - name: countLinesPerCommitPerAuthor
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les lignes par commits par personne
        date: 2021-09-01~2022-01-01
  - name: countLinesOverTime
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les lignes ajoutées par jour
        author: .*Claire.*
  - name: countFilesChanged
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les fichiers les plus changés
