path: ".."
plugins:
  - name: countLinesRemoved
    options:
      charts:
        - bar
        - doughnut
        - line
      valueOptions:
        displayName: Compter les lignes par personne
        width: 600
      toggleOptions:
        - nocolor
        - cute
